config/routes.rb
Rails.application.routes.draw do
 root 'home#index'
 get '/items/new', to: 'items#new'
 post '/items', to: 'items#create'
 get 'items/:id', to: 'items#show', as: :item
 resources :items 
 resources :line_items
 resource :carts, only: [:show, :index]
 resources :users, only: [:new, :create]
 resources :sessions, only: [:new, :create, :destroy]
 resources :charges
 get '/login', to: 'sessions#new'
 get 'logout', to: 'sessions#destroy'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :comments, dependent: :destroy
    after_initialize :set_defaults
    
    has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    def set_defaults
        if self.likes.nil?
            self.likes = 0
        end
    end
    
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  after_initialize :set_defaults
  has_many :line_items, dependent: :destroy
  before_save :set_subtotal
  belongs_to :user


  def subtotal
    line_items.collect {|line_item| line_item.valid? ? (line_item.unit_price*line_item.quantity) : 0 }.sum
  end

  def total_quantity
    line_items.collect {|line_item| line_item.valid? ? line_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end


  def set_defaults
      self.paid = false if self.paid.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    after_initialize :set_defaults
    validates :email, presence: true, uniqueness: true
    has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_many :orders, dependent: :destroy
    
    def cart
        cart = self.orders.find_by(paid: false)
        if cart 
            cart
        else
            Order.create(user: self)
        end
    end

    private

    def set_defaults
        self.admin = false if self.admin.nil?
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper

  private

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  def authorize
    redirect_to login_path, alert: "Not authorized - you must be logged in" if current_user.nil?
  end
  def authorize_admin
    redirect_to login_path, alert: "Not authorized - you must be logged in" unless !current_user.nil?  && current_user.admin
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show
        @line_items = current_user.cart.line_items
    end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    Stripe.api_key = ENV['SECRET_KEY']

    def new
    end
    
    def create
        # Amount in cents
        # @amount = 50000
        order = current_user.cart
        order.paid = true
        order.save

        redirect_to '/charges'
  
        # customer = Stripe::Customer.create(
        #   :email => params[:stripeEmail],
        #   :source  => params[:stripeToken]
        # )
      
        # charge = Stripe::Charge.create(
        #   :customer    => customer.id,
        #   :amount      => @amount,
        #   :description => 'BlacMarket Purchase',
        #   :currency    => 'usd'
        # )
      
      # rescue Stripe::CardError => e
      #   flash[:error] = e.message
      #   redirect_to root_path  
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @items = Item.all 
       
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authorize_admin, except: [:show, :index, :like]
    
    def index
        @items = Item.all
    end

    def new
        @item = Item.new
    end

    def create 
        @item = Item.new(params.require(:item).permit( :price, :content, :image, :title))

        if @item.save
            redirect_to root_path
        else
            render :new
        end
    end

    def show
        @item = Item.find(params[:id])
        @line_item = LineItem.new
    end

    def edit
        @item = Item.find(params[:id])
        
        
     
    end

    def update
        @item = Item.find(params[:id])
        if @item.update_attributes(item_params)
            flash[:success] = "Saved!"
            redirect_to root_path
        else
            render :edit
        end
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to items_path
    end

    def like
        @item = Item.find(params[:id])
        @item.likes +=1
        @item.save
        redirect_to item_path(@item)
    end

    private 
    def item_params
        params.require(:item).permit( :price, :content, :image, :title)
    end
    
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

    def create
        @line_item = LineItem.find_by(order: current_user.cart, item_id: params[:line_item][:item_id])
        if @line_item
            @line_item.quantity += 1
            @line_item.save
            session[:order_id]
        else
            @line_item = LineItem.new(line_item_params)
            @line_item.quantity = 1
            @line_item.order = current_user.cart
            @line_item.save
        end
        redirect_to carts_path
    end
    
    def update 
        @order = current_user.cart
        @line_item = @order.line_items.find(params[:id])
        @line_item.update_attributes(line_item_params)
        @line_item = @order.line_items
        redirect_to carts_path
    end
    
    def destroy
        @order = current_user.cart
        @line_item = @order.line_items.find(params[:id])
        @line_item.destroy
        @line_item = @order.line_items 
        redirect_to carts_path
    end

    private 

    def line_item_params
        params.require(:line_item).permit(:item_id, :quantity)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
    
    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id 
            redirect_to root_path, notice: "Logged in!"
        else
           flash.now.alert = "Invailded login Please try-again"
           render :new 
            end 
        end
    
        def destroy
          session[:user_id] = nil 
          session[:order_id] = nil
          redirect_to root_path, notice: "Logged out!"
        end
    end
    

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Congrats you are now a member of BlacMarket"
        redirect_to root_path
      else
        render :new
      end
    end
  
  
    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
       end
     
     
     end
     

app/helpers/application_helper.rb
module ApplicationHelper

    # def current_order 
    #     if session[:order_id]
    #         Order.find(session[:order_id])
    #     else
    #         @order = Order.new
    #         session[:order_id] = @order.id
    #         @order
    #     end
    # end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/carts/show.html.erb
    <table id="cart-table">
        <tbody>  
            <% @line_items.each do |product| %>
            
                    <tr>
                        <td><%= product.item.title  %></td>
                        
                        
                            <%= form_for product do |f|%>
                                <td><%= f.hidden_field :item_id, value: product.item.id %></td>
                                
                                <td><%= f.text_field :quantity, value: product.quantity.to_i, min: 1, class: 'col-sm-7 form-control' %></td>
                                <td class="money"><%= sprintf("$%.2f", product.item.price) %></td>
                                <td class="update"><%= f.submit "Update Quantity", class: 'btn btn-primary' %></td>
                            <% end %>
                        
                        <td><%= link_to "Delete", product, method: :delete, remote: true, class: 'btn btn-danger'%></td>
                    </tr>
            <% end %>
            <tr>
                <td colspan="4">Total Price:&nbsp;&nbsp; <%= @line_items.count > 0 ? sprintf("$%.2f", @line_items.collect {|line_item| line_item.valid? ? (line_item.unit_price*line_item.quantity) : 0 }.sum) : 'No Items Ordered' %></td>
            </tr>
        </tbody>
    </table>
    </br></br>

    <%= form_tag charges_path do %>
    <article>
        <% if flash[:error].present? %>
        <div id="error_explanation">
            <p><%= flash[:error] %></p>
        </div>
        <% end %>
    </article>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="BlacMarket Sale"
            data-amount="Current Cart"
            data-locale="auto">
    </script>

    <% end %>

app/views/charges/index.html.erb
<center>
<div class="thank_you">
    <h2>Thank you for your purchase</h2>
</div>

<h3>Your items are on the way!</h3>

<iframe src="https://giphy.com/embed/ygAmwHhCqZZMJY3wYh" width="480" height="360" frameBorder="0" class="" allowFullScreen>
</iframe>

</center>

app/views/home/index.html.erb
<center>

    <div class="col-md-12 col-md-offset-3">
        <table class ="table">
            <thead>
                <tr>
                <% @items.each do |item| %>
                <%= link_to (image_tag item.image.url) , item_path(item) %>
                    
                </tr>
            </thead>
            <tbody>   
                <% end %>
            </tbody>
        </table>
    </div>
</center>

app/views/items/edit.html.erb
<h5>Editing items</h5>



<%= form_for @item do |f| %>
    <div class="form-group">
        <%= f.label :title, "Title"%>
        <%= f.text_field :title, class: 'form-control' %>
   </div>
   <div class= "form-group">
        <%= f.label :price, "Price" %>
        <%= f.number_field :price, value: 1, class: 'form-control', min: 1 %>
  </div>
 <div class="form-group">
    <%= f.label :content, "Description" %>
    <%= f.text_area :content, class: 'form-control' %>
    <%= f.file_field :image %>
 </div>   
    <%= f.submit "Post", class: 'btn btn-success' %>
    <% end %>


<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= link_to  "New Item", items_new_path %>

<div class="col-md-6 col-md-offset-3">
    <table class ="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Price</th>
                <th>Likes</th>
                <th>Date</th>
             </tr>
        </thead>
        <tbody>   
            <% @items.each do |item| %>
                <tr>
                    <td><%= item.title%></td>
                    <td><%= item.price %></td>
                    
                    <td><%= item.created_at %></td>
                
                    <td>
                        <%# if @item.user.id = current_user.id%>
                        <%= link_to "Edit", edit_item_path(item)%>
                        <%= link_to "Delete", item_path(item), method: :delete %>
                    
                    </td>    
                </tr>
                
            <% end %>
        </tbody>
    </table>
</div>

app/views/items/new.html.erb
<%= form_for @item do |f| %>
    <div class="form-group">
        <%= f.label :title, "Title"%>
        <%= f.text_field :title, class: 'form-control' %>
   </div>
   <div class= "form-group">
        <%= f.label :price, "Price" %>
        <%= f.number_field :price, value: 1, class: 'form-control', min: 1 %>
  </div>
 <div class="form-group">
    <%= f.label :content, "Comment" %>
    <%= f.text_area :content, class: 'form-control' %>
    <%= f.file_field :image %>
 </div>   
    <%= f.submit "Post", class: 'btn btn-success' %>
    <% end %>

app/views/items/show.html.erb
</br>
<%=link_to "All Posts", items_path%>
<%= link_to "New Posts", items_new_path%>

<%= form_for(@item) do |f|%>

    <p><%= @item.title %></p>
    <p><%= image_tag @item.image.url%></p>
    <p><%= @item.content%></p>
    <p>
     <%= sprintf("$%.2f", @item.price)%>
    </p>
    

<% end %>

<div class ="add_cart_show"><%= form_for(@line_item) do |f|%>
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.hidden_field :quantity, value: @line_item.quantity.to_i, min: 1, class: "form-control" %>
    <%= f.submit "Add to cart", class: 'btn btn-primary btn-sm'%>   
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blacmarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-3">
    <div class="container">
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <h1><%= link_to "BlacMarket", root_path %></h1> 
          <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <% if current_user %><span class="text-warning">Welcome, <%= current_user.name %></span>
              <% if current_user.admin %>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <%= link_to 'Manage Items', items_path, class: "text-danger" %>
              <% end %>
              &nbsp;&nbsp;|&nbsp;&nbsp;
              <%= link_to 'Log Out', session_path('dummy'), method: :delete, class: "text-danger" %>
            <% else %>
              <%= link_to 'Sign In', login_path, class: "text-warning" %>
              &nbsp;&nbsp;|&nbsp;&nbsp;
              <%= link_to 'Sign Up', new_user_path, class: "text-danger" %>
            <% end %>
            </li>
            <% if current_user %>
              <li class="nav-item">
                <%= link_to(carts_path) do %>
                  <div class="fas fa-shopping-cart"></div>
                  <span id="qty-count" class="badge badge-danger badge-pill"><%= current_user.cart.total_quantity %></span>
                <% end %>
              </li>
            <% end %>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input type="text" class="form-control mr-sm-2" placeholder="Search">
            <button class="btn btn-outline-warning my-2 my-sm-0">Search</button>
          </form>
        </div>  
      </div>
    </nav>             
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/new.html.erb
<center>
<div class="create_account">
<h1>Create Account</h1>
</div>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @user do |f| %>
  <div class="field">
  
    <%= f.text_field :name, placeholder: "Name" %>
  </div></br>
  <div class="field">
  
    <%= f.text_field :email, placeholder: 'Email' %>
  </div></br>
  <div class="field">
 
    <%= f.password_field :password, placeholder: 'Password' %>
  </div></br>
  <div class="field">
   
    <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %>
  </div> 
  </br>
  <div class="actions"><%= submit_tag "Create", class: "btn btn-outline-danger" %></div>
  </center>
<% end %>